using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using DicomTemplateMakerGUI.DicomTemplateServices;
using DicomTemplateMakerGUI.Services;

namespace DicomTemplateMakerGUI.Shell
{
    /// <summary>A template and the folders it monitors.</summary>
    public sealed record MonitoredTemplate(string Name, IReadOnlyList<string> Paths);

    /// <summary>The main window's confirmations and reports. Every destructive action states exactly what will happen.</summary>
    public static class ShellMessages
    {
        private static readonly string Paragraph = Environment.NewLine + Environment.NewLine;

        /// <summary>Asked when a bulk action finds no selected template: act on all of them instead?</summary>
        public static string UseAllTemplates(string action, int total, int hiddenSelected)
        {
            var text = new StringBuilder("No templates are selected");
            text.Append(hiddenSelected > 0 ? $" among the templates shown ({Text.Count(hiddenSelected, "selected template")} {Text.IsAre(hiddenSelected)} hidden by the search)." : ".");
            text.Append(Paragraph).Append(action).Append(" all ").Append(Text.Count(total, "template")).Append('?');
            return text.ToString();
        }

        /// <summary>The sentence about selected templates hidden by the search, which bulk actions leave out; empty when there are none.</summary>
        public static string HiddenNote(int hiddenSelected)
        {
            return hiddenSelected == 0
                ? string.Empty
                : $"{Text.Count(hiddenSelected, "selected template")} hidden by the current search {Text.IsAre(hiddenSelected)} left out. Clear the search to include {(hiddenSelected == 1 ? "it" : "them")}.";
        }

        /// <summary>Confirms "Delete previously generated RTs", naming the templates and the folders that will be searched.</summary>
        public static string ConfirmDeleteGenerated(IReadOnlyList<MonitoredTemplate> templates, int hiddenSelected, RunnerState runnerState)
        {
            ArgumentNullException.ThrowIfNull(templates);
            List<MonitoredTemplate> withPaths = templates.Where(t => t.Paths.Count > 0).ToList();
            List<string> withoutPaths = templates.Where(t => t.Paths.Count == 0).Select(t => t.Name).ToList();
            var text = new StringBuilder();
            text.Append("Delete the RTs generated by ").Append(Text.Count(withPaths.Count, "template")).Append('?').Append(Paragraph);
            text.AppendLine("These folders, and all folders inside them, will be searched:");
            var lines = new List<string>();
            foreach (MonitoredTemplate template in withPaths)
            {
                lines.Add(template.Name + ": " + string.Join("; ", template.Paths));
            }

            text.AppendLine(Text.List(lines, 12));
            text.AppendLine();
            text.Append("Only files named <template>_UID<series UID>.dcm written by these templates are deleted. They are deleted permanently, "
                + "not moved to the Recycle Bin; other files are not touched.");
            if (withoutPaths.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(withoutPaths.Count, "selected template")).Append(" without monitored folders ")
                    .Append(withoutPaths.Count == 1 ? "has" : "have").Append(" nothing to delete: ").Append(string.Join(", ", withoutPaths.Take(10)))
                    .Append(withoutPaths.Count > 10 ? ", …" : string.Empty).Append('.');
            }

            if (hiddenSelected > 0)
            {
                text.Append(Paragraph).Append(HiddenNote(hiddenSelected));
            }

            // A running generator writes an RT for every matching series that has none, so it would write the deleted
            // ones again within one scan: it is stopped for the delete and left stopped.
            text.Append(Paragraph);
            if (runnerState != RunnerState.Stopped)
            {
                text.Append("The RT generator is stopped before deleting and stays stopped afterwards. ");
            }

            text.Append("Whenever the RT generator runs, it writes a new RT, with the template as it is then, for every matching series in these folders "
                + "that has none, so the deleted RTs come back within seconds of starting it. To keep them deleted, first remove these folders from the "
                + "templates' monitored folders or change their DICOM requirements. An RT generator running elsewhere on these folders (the command-line "
                + "tool, or this program on another computer) writes them again straight away.");
            return text.ToString();
        }

        /// <summary>The result of deleting generated RTs: the count deleted and every failure.</summary>
        /// <param name="report">What was deleted.</param>
        /// <param name="generatorStopped">True when the RT generator was running and was stopped for the delete.</param>
        public static string DescribeDeleteGenerated(DeleteReport report, bool generatorStopped = false)
        {
            ArgumentNullException.ThrowIfNull(report);
            var text = new StringBuilder();
            text.Append("Deleted ").Append(Text.Count(report.Deleted.Count, "generated RT")).Append('.');
            if (report.Failed.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(report.Failed.Count, "file")).Append(" could not be deleted:").AppendLine()
                    .Append(Text.List(report.Failed.Select(f => f.Path + ": " + f.Message)));
            }

            if (report.Errors.Count > 0)
            {
                text.Append(Paragraph).Append("These could not be searched:").AppendLine()
                    .Append(Text.List(report.Errors.Select(e => e.Context + ": " + e.Message)));
            }

            if (report.HasFailures)
            {
                text.Append(Paragraph).Append("The details are in the log.");
            }

            if (generatorStopped)
            {
                text.Append(Paragraph).Append("The RT generator is stopped. When you start it again, it writes RTs again for the matching series that have none, "
                    + "using the templates as they are then.");
            }

            return text.ToString();
        }

        /// <summary>
        /// Confirms moving template folders to the Recycle Bin. <paramref name="notRecyclable"/> are the selected folders
        /// that have no Recycle Bin (see <see cref="RecycleBinRule"/>): they are named as not deleted.
        /// </summary>
        public static string ConfirmDeleteTemplates(IReadOnlyList<(string Name, string Folder)> templates, int hiddenSelected, IReadOnlyList<NotRecyclable>? notRecyclable = null)
        {
            ArgumentNullException.ThrowIfNull(templates);
            var text = new StringBuilder();
            text.Append("Move ").Append(Text.Count(templates.Count, "template folder")).Append(" to the Recycle Bin?").Append(Paragraph);
            text.AppendLine(Text.List(templates.Select(t => t.Name + "  (" + t.Folder + ")"), 20));
            text.AppendLine();
            text.Append("Their ROIs, monitored folders and DICOM requirements go with them; they can be restored from the Recycle Bin. "
                + "RTs they generated earlier are not deleted, and no new RTs are written for them. "
                + "Windows may ask again; if it cannot recycle a folder, it asks before deleting it permanently.");
            if (notRecyclable != null && notRecyclable.Count > 0)
            {
                text.Append(Paragraph).Append(DescribeNotRecyclable(notRecyclable));
            }

            if (hiddenSelected > 0)
            {
                text.Append(Paragraph).Append(HiddenNote(hiddenSelected));
            }

            return text.ToString();
        }

        /// <summary>The selected template folders that are not deleted because they have no Recycle Bin, and what to do instead.</summary>
        public static string DescribeNotRecyclable(IReadOnlyList<NotRecyclable> notRecyclable)
        {
            ArgumentNullException.ThrowIfNull(notRecyclable);
            return (notRecyclable.Count == 1 ? "This template folder is not deleted, because " : $"These {notRecyclable.Count} template folders are not deleted, because ")
                + "deleting there would be permanent (no Recycle Bin):" + Environment.NewLine
                + Text.List(notRecyclable.Select(n => n.Name + "  (" + n.Folder + "): " + n.Reason), 20) + Environment.NewLine
                + "To delete " + (notRecyclable.Count == 1 ? "it" : "them") + " anyway, use File Explorer, or copy "
                + (notRecyclable.Count == 1 ? "it" : "them") + " somewhere safe first.";
        }

        /// <summary>The result of moving template folders to the Recycle Bin.</summary>
        public static string DescribeDeleteTemplates(BulkFolderResult result)
        {
            ArgumentNullException.ThrowIfNull(result);
            var text = new StringBuilder();
            text.Append("Moved ").Append(Text.Count(result.Done.Count, "template folder")).Append(" to the Recycle Bin.");
            if (result.Failed.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(result.Failed.Count, "template folder")).Append(result.Failed.Count == 1 ? " was" : " were")
                    .Append(" not moved and ").Append(result.Failed.Count == 1 ? "is" : "are").Append(" unchanged:").AppendLine()
                    .Append(Text.List(result.Failed.Select(f => f.Folder + ": " + f.Message)))
                    .Append(Paragraph).Append("The details are in the log.");
            }

            return text.ToString();
        }

        /// <summary>Confirms "Create folder with loadable RTs".</summary>
        public static string ConfirmTestRts(IReadOnlyList<string> templateNames, string outputFolder, int hiddenSelected)
        {
            ArgumentNullException.ThrowIfNull(templateNames);
            var text = new StringBuilder();
            text.Append("Generate test RTs for ").Append(Text.Count(templateNames.Count, "template")).Append(" into ").Append(outputFolder).Append('?').Append(Paragraph);
            text.AppendLine(Text.List(templateNames, 15));
            text.AppendLine();
            text.Append("A four-slice sample CT is copied into the folder and each template writes one RT for it, so the RTs can be loaded into a planning system to check the templates. "
                + "Files already in the folder are kept. The templates' monitored folders are not changed and the RT generator is not started.");
            if (hiddenSelected > 0)
            {
                text.Append(Paragraph).Append(HiddenNote(hiddenSelected));
            }

            return text.ToString();
        }

        /// <summary>The result of "Create folder with loadable RTs": RTs written and every template that got none, with why.</summary>
        public static string DescribeTestRts(TestRtResult result)
        {
            ArgumentNullException.ThrowIfNull(result);
            var text = new StringBuilder();
            if (result.Errors.Count > 0)
            {
                text.Append("No test RTs were written.").Append(Paragraph).Append(Text.List(result.Errors));
                return text.ToString();
            }

            text.Append("Wrote ").Append(Text.Count(result.WrittenCount, "test RT")).Append(" into ").Append(result.OutputFolder).Append('.');
            var notWritten = new List<string>();
            var roiLines = new List<string>();
            foreach ((string template, RunReport report) in result.Reports)
            {
                if (report.WrittenCount == 0)
                {
                    notWritten.Add(template + ": " + WhyNoTestRt(report));
                }

                roiLines.AddRange(report.RoiFailures.Select(f => $"{template}: ROI '{f.RoiName}' left out: {f.Reason}"));
            }

            if (notWritten.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(notWritten.Count, "template")).Append(" wrote no RT:").AppendLine().Append(Text.List(notWritten));
            }

            if (roiLines.Count > 0)
            {
                text.Append(Paragraph).Append("ROIs left out of the written RTs:").AppendLine().Append(Text.List(roiLines));
            }

            return text.ToString();
        }

        /// <summary>Asks before replacing existing Varian XML files, listing them.</summary>
        public static string ConfirmExportOverwrite(string outputFolder, IReadOnlyList<string> existingFiles, int total)
        {
            ArgumentNullException.ThrowIfNull(existingFiles);
            var text = new StringBuilder();
            text.Append(existingFiles.Count == 1 ? "This file already exists in " : $"These {existingFiles.Count} files already exist in ")
                .Append(outputFolder).Append(':').AppendLine().AppendLine(Text.List(existingFiles, 20)).AppendLine();
            text.Append("Replace ").Append(existingFiles.Count == 1 ? "it" : "them").Append('?').Append(Paragraph)
                .Append("Yes: replace ").Append(existingFiles.Count == 1 ? "it" : "them").Append(" and write the other ").Append(total - existingFiles.Count).Append(".").AppendLine()
                .Append("No: keep ").Append(existingFiles.Count == 1 ? "it" : "them").Append(" and write only the other ").Append(total - existingFiles.Count).Append('.').AppendLine()
                .Append("Cancel: write nothing.");
            return text.ToString();
        }

        /// <summary>The result of a Varian XML export.</summary>
        public static string DescribeExport(VarianExportResult result)
        {
            ArgumentNullException.ThrowIfNull(result);
            var text = new StringBuilder();
            text.Append("Wrote ").Append(Text.Count(result.Written.Count, "Varian XML file")).Append(" to ").Append(result.OutputFolder).Append('.');
            if (result.SkippedExisting.Count > 0)
            {
                text.Append(Paragraph).Append("Kept ").Append(Text.Count(result.SkippedExisting.Count, "existing file")).Append(" unchanged: ")
                    .Append(string.Join(", ", result.SkippedExisting.Take(20))).Append(result.SkippedExisting.Count > 20 ? ", …" : string.Empty).Append('.');
            }

            if (result.Failed.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(result.Failed.Count, "template")).Append(result.Failed.Count == 1 ? " was" : " were").Append(" not exported:").AppendLine()
                    .Append(Text.List(result.Failed.Select(f => f.Template + ": " + f.Reason)));
            }

            List<string> skipped = result.Written
                .SelectMany(r => r.SkippedStructures.Select(s => $"{Path.GetFileName(r.Source)}: ROI '{s.Structure}' left out: {s.SkipReason}"))
                .ToList();
            if (skipped.Count > 0)
            {
                text.Append(Paragraph).Append("ROIs left out of the written files:").AppendLine().Append(Text.List(skipped));
            }

            return text.ToString();
        }

        /// <summary>Asks before an import replaces existing templates.</summary>
        public static string ConfirmImportReplace(string templateRoot, IReadOnlyList<string> existingTemplates, int importable)
        {
            ArgumentNullException.ThrowIfNull(existingTemplates);
            var text = new StringBuilder();
            text.Append(existingTemplates.Count == 1 ? "This template already exists in " : $"These {existingTemplates.Count} templates already exist in ")
                .Append(templateRoot).Append(':').AppendLine().AppendLine(Text.List(existingTemplates, 20)).AppendLine();
            text.Append("Importing replaces ").Append(existingTemplates.Count == 1 ? "its" : "their").Append(" ROIs with the ones in the XML file")
                .Append(existingTemplates.Count == 1 ? "" : "s").Append("; monitored folders and DICOM requirements are kept.").Append(Paragraph);
            int others = importable - existingTemplates.Count;
            text.Append("Yes: replace ").Append(existingTemplates.Count == 1 ? "it" : "them").Append(" and import the other ").Append(others).Append('.').AppendLine()
                .Append("No: keep ").Append(existingTemplates.Count == 1 ? "it" : "them").Append(" unchanged and import only the other ").Append(others).Append('.').AppendLine()
                .Append("Cancel: import nothing.");
            return text.ToString();
        }

        /// <summary>The result of a Varian XML import: imported templates, failed files and skipped structures.</summary>
        public static string DescribeImport(VarianImportResult result)
        {
            ArgumentNullException.ThrowIfNull(result);
            List<VarianXmlReport> imported = result.Imported.ToList();
            var text = new StringBuilder();
            text.Append("Imported ").Append(Text.Count(imported.Count, "template")).Append(" into ").Append(result.TemplateRoot);
            text.Append(imported.Count == 0 ? "." : ":" + Environment.NewLine + Text.List(imported.Select(r => Path.GetFileName(r.Target ?? r.Source) + $" ({Text.Count(r.SucceededCount, "ROI")})"), 20));
            if (result.SkippedExisting.Count > 0)
            {
                text.Append(Paragraph).Append("Kept ").Append(Text.Count(result.SkippedExisting.Count, "existing template")).Append(" unchanged: ")
                    .Append(string.Join(", ", result.SkippedExisting.Take(20))).Append(result.SkippedExisting.Count > 20 ? ", …" : string.Empty).Append('.');
            }

            List<string> failed = result.FailedReports.Select(r => Path.GetFileName(r.Source) + ": " + r.Error)
                .Concat(result.NotImported.Select(n => Path.GetFileName(n.File) + ": " + n.Reason))
                .ToList();
            if (failed.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(failed.Count, "file")).Append(failed.Count == 1 ? " was" : " were").Append(" not imported:").AppendLine().Append(Text.List(failed));
            }

            List<string> skipped = imported
                .SelectMany(r => r.SkippedStructures.Select(s => $"{Path.GetFileName(r.Target ?? r.Source)}: structure '{s.Structure}' left out: {s.SkipReason}"))
                .ToList();
            if (skipped.Count > 0)
            {
                text.Append(Paragraph).Append("Structures left out of the imported templates:").AppendLine().Append(Text.List(skipped));
            }

            return text.ToString();
        }

        /// <summary>
        /// Asked (Yes/No/Cancel) when the template folder is changed while the RT generator runs: restarting it on the new
        /// folder makes that folder's templates write RTs into the folders they monitor.
        /// </summary>
        public static string ConfirmChangeRootWhileRunning(string newRoot)
        {
            return "The RT generator is running on the current template folder." + Paragraph
                + "Yes: switch to " + newRoot + " and keep the RT generator running there. It then writes RTs for the templates in that folder "
                + "into the folders they monitor (each template's Paths.txt), starting within seconds." + Environment.NewLine
                + "No: switch to " + newRoot + " and stop the RT generator (for example to edit a test or draft template library). Start it again when you want RTs." + Environment.NewLine
                + "Cancel: keep the current template folder.";
        }

        /// <summary>
        /// Confirms writing templates from the main window to a shared Airtable table, naming the table, each template
        /// with its ROI count, and the selected templates left out because the search hides them.
        /// </summary>
        public static string ConfirmAirtableWrite(string table, IReadOnlyList<(string Name, int RoiCount)> templates, int hiddenSelected)
        {
            ArgumentNullException.ThrowIfNull(templates);
            var text = new StringBuilder();
            text.Append("Update table \"").Append(table).Append("\" with ").Append(Text.Count(templates.Count, "template")).Append('?').Append(Paragraph);
            text.AppendLine(Text.List(templates.Select(t => t.Name + " (" + Text.Count(t.RoiCount, "ROI") + ")"), 20));
            text.AppendLine();
            text.Append("Each ROI is one record shared by every site in the table: shared fields such as colour, DVH style, interpreted type and "
                + "ontology codes change for every site that uses the structure. Each template is added to its ROIs' recommended or optional lists; "
                + "the other sites' lists are kept. The templates are sent as they were read when the template list was last loaded.");
            if (hiddenSelected > 0)
            {
                text.Append(Paragraph).Append(HiddenNote(hiddenSelected));
            }

            return text.ToString();
        }

        /// <summary>The result of "Copy selected": the copies made (without monitored folders) and the templates not copied.</summary>
        public static string DescribeCopies(IReadOnlyList<(string Source, string Copy)> copies, IReadOnlyList<string> failures)
        {
            ArgumentNullException.ThrowIfNull(copies);
            ArgumentNullException.ThrowIfNull(failures);
            var text = new StringBuilder();
            text.Append("Copied ").Append(Text.Count(copies.Count, "template")).Append(copies.Count == 0 ? "." : ":" + Environment.NewLine + Text.List(copies.Select(c => c.Source + " → " + c.Copy), 20));
            if (copies.Count > 0)
            {
                text.Append(Paragraph).Append(copies.Count == 1 ? "The copy has" : "The copies have")
                    .Append(" the same ROIs and DICOM requirements but no monitored folders, so the RT generator writes no RTs for ")
                    .Append(copies.Count == 1 ? "it" : "them").Append(". Add monitored folders in ").Append(copies.Count == 1 ? "its" : "each copy's")
                    .Append(" editor when it is ready.");
            }

            if (failures.Count > 0)
            {
                text.Append(Paragraph).Append(failures.Count == 1 ? "This template was" : "These templates were").Append(" not copied:").AppendLine()
                    .Append(Text.List(failures, 20)).Append(Paragraph).Append("The details are in the log.");
            }

            return text.ToString();
        }

        /// <summary>Asked when the chosen template folder holds no templates (a wrong click, or a new setup).</summary>
        public static string ConfirmFolderWithoutTemplates(string folder)
        {
            return $"{folder} holds no templates (no Ontologies folder and no template folders)."
                + Paragraph + "Use it as the template folder anyway? New templates will be created there.";
        }

        /// <summary>The one-line summary in the problems panel; empty when there are none.</summary>
        public static string ProblemsLine(IReadOnlyList<TemplateProblem> problems)
        {
            ArgumentNullException.ThrowIfNull(problems);
            if (problems.Count == 0)
            {
                return string.Empty;
            }

            var parts = new List<string>();
            if (problems.Any(p => p.Kind == TemplateProblemKind.LibraryUnreadable))
            {
                parts.Add("the ontology library cannot be read, so no template is listed");
            }

            if (problems.Any(p => p.Kind == TemplateProblemKind.FolderUnreadable))
            {
                parts.Add("the template folder cannot be read");
            }

            int unreadable = problems.Where(p => p.Kind == TemplateProblemKind.TemplateUnreadable).Select(p => p.Subject).Distinct().Count();
            if (unreadable > 0)
            {
                parts.Add(Text.Count(unreadable, "template") + " cannot be read and " + (unreadable == 1 ? "is" : "are") + " not listed");
            }

            int legacy = problems.Where(p => p.Kind == TemplateProblemKind.LegacyFilesKept).Select(p => p.Subject).Distinct().Count();
            if (legacy > 0)
            {
                parts.Add(Text.Count(legacy, "template") + (legacy == 1 ? " has" : " have") + " legacy files that were kept");
            }

            if (problems.Any(p => p.Kind == TemplateProblemKind.LibraryNotUpdated))
            {
                parts.Add("the ontology library could not be updated");
            }

            string line = string.Join("; ", parts);
            return "⚠ " + char.ToUpperInvariant(line[0]) + line.Substring(1) + ".";
        }

        /// <summary>Every problem, for the Details button and the problems tooltip.</summary>
        public static string ProblemsDetails(IReadOnlyList<TemplateProblem> problems, int max = 30)
        {
            ArgumentNullException.ThrowIfNull(problems);
            return Text.List(problems.Select(p => p.Describe()), max, "• ").Replace(Environment.NewLine, Paragraph)
                + Paragraph + "Files that cannot be read are left unchanged and nothing is saved over them. Repair or remove them, then change or reopen the template folder.";
        }

        /// <summary>The message box for problems not shown before this session.</summary>
        public static string NewProblems(IReadOnlyList<TemplateProblem> problems)
        {
            ArgumentNullException.ThrowIfNull(problems);
            return (problems.Count == 1 ? "A problem was found in the template folder:" : $"{problems.Count} problems were found in the template folder:")
                + Paragraph + ProblemsDetails(problems, 10)
                + Paragraph + "They stay listed under the templates; this message is not shown again for them.";
        }

        /// <summary>The message for an unexpected error caught by the global handler.</summary>
        public static string UnexpectedError(Exception exception, string logsFolder)
        {
            ArgumentNullException.ThrowIfNull(exception);
            return "Something went wrong: " + exception.Message
                + Paragraph + "The details are in the log in " + logsFolder + " (use \"Open log folder\")."
                + Paragraph + "The program tries to continue. If it behaves oddly, close it and start it again.";
        }

        private static string WhyNoTestRt(RunReport report)
        {
            if (report.Errors.Count > 0)
            {
                return string.Join(" ", report.Errors.Select(e => e.Message));
            }

            if (report.Count(SkipReason.AlreadyDone) > 0)
            {
                return "a test RT for the sample CT is already in the folder.";
            }

            if (report.Count(SkipReason.NoMatch) > 0)
            {
                return "the sample CT does not meet the template's DICOM requirements (Series or Study Description).";
            }

            SkippedItem? skipped = report.Skipped.FirstOrDefault();
            return skipped != null ? skipped.Reason + ": " + skipped.Detail : "no image series was found.";
        }
    }
}
