using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DicomTemplateMakerGUI.Shell;
using ROIOntologyClass;

namespace DicomTemplateMakerGUI.Editors
{
    /// <summary>The editor windows' confirmations and reports. Every overwrite states exactly what will change.</summary>
    public static class EditorMessages
    {
        private static readonly string Paragraph = Environment.NewLine + Environment.NewLine;

        /// <summary>Asked before "Build template" replaces a template that already exists.</summary>
        /// <param name="existingRoiCount">The ROIs the existing template has; null when they cannot be counted.</param>
        /// <param name="newRoiCount">The ROIs this window would save.</param>
        public static string ConfirmReplaceTemplate(string name, string folder, int? existingRoiCount, int newRoiCount)
        {
            var text = new StringBuilder();
            text.Append("A template named \"").Append(name).Append("\" already exists in ").Append(folder);
            text.Append(existingRoiCount.HasValue ? " (" + Text.Count(existingRoiCount.Value, "ROI") + ")." : ".");
            text.Append(Paragraph).Append("Building replaces its ROIs with the ").Append(newRoiCount == 0 ? "ROIs in this window (none yet)" : Text.Count(newRoiCount, "ROI") + " in this window")
                .Append(". Its monitored folders and DICOM requirements are kept.");
            text.Append(Paragraph).Append("To change the existing template instead, press No and use its \"Edit ROIs and monitored DICOM paths\" button in the main window.");
            text.Append(Paragraph).Append("Replace the ROIs of \"").Append(name).Append("\"?");
            return text.ToString();
        }

        /// <summary>Asked before the editor writes a template to an Airtable table.</summary>
        public static string ConfirmAirtableWrite(string table, string template, int roiCount, bool saveFirst)
        {
            var text = new StringBuilder();
            text.Append("Update table \"").Append(table).Append("\" with template \"").Append(template).Append("\" (").Append(Text.Count(roiCount, "ROI")).Append(")?");
            text.Append(Paragraph).Append("Each ROI is one record shared by every site in the table: shared fields such as colour, DVH style, interpreted type and "
                + "ontology codes change for every site that uses the structure. \"").Append(template)
                .Append("\" is added to each ROI's recommended or optional list; the other sites' lists are kept.");
            if (saveFirst)
            {
                text.Append(Paragraph).Append("The template is saved first, so the table gets what is saved on disk.");
            }

            return text.ToString();
        }

        /// <summary>Asked when a window with unsaved changes is closed.</summary>
        public static string UnsavedChanges(string what)
        {
            return "Save the changes to " + what + " before closing?" + Paragraph
                + "Yes saves them. No discards them. Cancel keeps the window open.";
        }

        /// <summary>Why renaming a template failed; the folder is unchanged.</summary>
        public static string RenameFailed(string folder, string newName, string reason)
        {
            return "The template could not be renamed to \"" + newName + "\": " + reason + Paragraph
                + "The folder " + folder + " was left as it was. A file in it may be open in another program (for example a viewer, "
                + "or the RT generator reading it); close it and try again.";
        }

        /// <summary>What renaming a template with monitored folders does to its generated RTs.</summary>
        public static string RenameConsequences(string oldName)
        {
            return "RTs already generated by this template keep the old name (" + oldName + "_UID….dcm), and \"Delete previously generated RTs\" "
                + "no longer finds them under the new name. The RT generator writes a new RT, named after the new name, for each matching series "
                + "in the monitored folders, next to the old one. To avoid having both, delete the generated RTs before renaming.";
        }

        /// <summary>Asked before deleting a library entry; names the templates that use it.</summary>
        public static string ConfirmDeleteOntology(OntologyCodeClass entry, IReadOnlyList<string> templatesUsingIt)
        {
            ArgumentNullException.ThrowIfNull(entry);
            ArgumentNullException.ThrowIfNull(templatesUsingIt);
            var text = new StringBuilder();
            text.Append("Delete \"").Append(entry.CodeMeaning).Append("\" (code ").Append(entry.CodeValue ?? "none").Append(", ").Append(entry.Scheme ?? "no scheme")
                .Append(") from the ontology library?");
            if (templatesUsingIt.Count > 0)
            {
                text.Append(Paragraph).Append("It is used by ").Append(Text.Count(templatesUsingIt.Count, "template")).Append(':').AppendLine()
                    .Append(Text.List(templatesUsingIt, 10));
                text.Append(Paragraph).Append("Those templates keep the code: deleting it only removes it from the list offered when adding ROIs, "
                    + "and it is added back to the library the next time the templates are read. To stop using it, change those ROIs' ontology first.");
            }

            text.Append(Paragraph).Append("The deletion is saved when you press Save.");
            return text.ToString();
        }

        /// <summary>Asked before converting codes from one scheme to the other.</summary>
        public static string ConfirmSchemeConversion(SchemeConversionPlan plan, string fromName, string toName)
        {
            ArgumentNullException.ThrowIfNull(plan);
            var text = new StringBuilder();
            text.Append("Convert codes from ").Append(fromName).Append(" to ").Append(toName).Append('?').Append(Paragraph);
            var lines = new List<string>();
            if (plan.RoiCount > 0)
            {
                lines.Add(Text.Count(plan.RoiCount, "ROI") + " in " + Text.Count(plan.TemplateCount, "template") + ": "
                    + string.Join(", ", plan.Templates.Take(8).Select(t => t.Template + " (" + t.Rois + ")")) + (plan.TemplateCount > 8 ? ", …" : string.Empty));
            }

            if (plan.LibraryEntryCount > 0)
            {
                lines.Add(Text.Count(plan.LibraryEntryCount, "entry", "entries") + " of the ontology library");
            }

            text.AppendLine(Text.List(lines));
            text.AppendLine();
            text.Append("Each of these templates is saved (its All_ROIs.json is replaced), and so is the ontology library.");
            int left = plan.RoisWithoutEquivalent + plan.LibraryEntriesWithoutEquivalent;
            if (left > 0)
            {
                text.Append(Paragraph).Append("Left unchanged because the table has no ").Append(toName).Append(" equivalent: ")
                    .Append(Text.Count(plan.RoisWithoutEquivalent, "ROI")).Append(" and ")
                    .Append(Text.Count(plan.LibraryEntriesWithoutEquivalent, "library entry", "library entries")).Append('.');
            }

            text.Append(Paragraph).Append("Converting back uses the reverse table, which may not restore every original code.");
            return text.ToString();
        }

        /// <summary>Shown when nothing would change.</summary>
        public static string NothingToConvert(SchemeConversionPlan plan, string fromName, string toName)
        {
            ArgumentNullException.ThrowIfNull(plan);
            string text = "No template ROI or library entry has a " + fromName + " code with a " + toName + " equivalent, so nothing was changed.";
            int left = plan.RoisWithoutEquivalent + plan.LibraryEntriesWithoutEquivalent;
            return left == 0 ? text : text + Paragraph + Text.Count(left, fromName + " code") + " without an equivalent " + (left == 1 ? "was" : "were") + " found.";
        }

        /// <summary>The report after a conversion.</summary>
        public static string DescribeSchemeConversion(SchemeConversionResult result, string fromName, string toName)
        {
            ArgumentNullException.ThrowIfNull(result);
            var text = new StringBuilder();
            text.Append("Converted from ").Append(fromName).Append(" to ").Append(toName).Append(": ")
                .Append(Text.Count(result.RoisChanged, "ROI")).Append(" in ").Append(Text.Count(result.TemplatesSaved.Count, "template"))
                .Append(", and ").Append(Text.Count(result.LibraryEntriesChanged, "library entry", "library entries")).Append('.');
            if (result.LibraryEntriesMerged > 0)
            {
                text.Append(Paragraph).Append(Text.Count(result.LibraryEntriesMerged, "converted library entry", "converted library entries"))
                    .Append(result.LibraryEntriesMerged == 1 ? " was" : " were").Append(" merged with an entry that already had the new code.");
            }

            if (result.Failures.Count > 0)
            {
                text.Append(Paragraph).Append(Text.Count(result.Failures.Count, "template")).Append(" could not be saved and ")
                    .Append(result.Failures.Count == 1 ? "is" : "are").Append(" unchanged on disk:").AppendLine().Append(Text.List(result.Failures, 10));
            }

            return text.ToString();
        }

        /// <summary>Why the ontology library was not saved: the entries changed in this window that still have a problem.</summary>
        public static string OntologyNotSaved(IReadOnlyList<string> problems)
        {
            ArgumentNullException.ThrowIfNull(problems);
            return "The ontology library was not saved. Fix " + (problems.Count == 1 ? "this entry" : "these " + problems.Count + " entries") + " first:"
                + Environment.NewLine + Text.List(problems, 10);
        }
    }
}
