using DicomTemplateMakerGUI.DicomTemplateServices;

// Usage: DicomTemplateMakerCSharp [template-folder] [--once] [--delete-generated]
//   template-folder     folder holding one sub-folder per template (default: current folder)
//   --once              process every template once and exit (default: keep watching every 3 s)
//   --delete-generated  delete RT Structure files previously generated by these templates, then exit
string templateFolder = ".";
bool once = false;
bool deleteGenerated = false;
foreach (string arg in args)
{
    switch (arg)
    {
        case "--once":
            once = true;
            break;
        case "--delete-generated":
            deleteGenerated = true;
            break;
        case "-h":
        case "--help":
            Console.WriteLine("Usage: DicomTemplateMakerCSharp [template-folder] [--once] [--delete-generated]");
            return 0;
        default:
            templateFolder = arg;
            break;
    }
}

if (!Directory.Exists(templateFolder))
{
    Console.Error.WriteLine($"Template folder not found: {Path.GetFullPath(templateFolder)}");
    return 2;
}

string templateRs = Path.Combine(AppContext.BaseDirectory, "template_RS.dcm");
var runner = new DicomTemplateRunner(Path.GetFullPath(templateFolder), templateRs);
if (deleteGenerated)
{
    runner.delete_rts();
    return 0;
}

if (once)
{
    runner.build_dictionary();
    runner.walk_down_folders(false);
    return 0;
}

Console.WriteLine($"Watching templates in {Path.GetFullPath(templateFolder)}. Press Ctrl+C to stop.");
runner.run();
return 0;
