using DicomTemplateMakerGUI.DicomTemplateServices;
using Microsoft.Extensions.Logging;

// Usage: DicomTemplateMakerCSharp [template-folder] [--once] [--delete-generated]
//   template-folder     folder holding one sub-folder per template (default: current folder)
//   --once              process every template once and exit (default: keep watching every 3 s)
//   --delete-generated  delete RT Structure files previously generated by these templates, then exit
// Exit codes: 0 success; 1 errors (in a --once or --delete-generated run, or it was cancelled); 2 bad arguments.
// Ctrl+C stops after the current directory; a second Ctrl+C ends the process at once.
const string Usage = "Usage: DicomTemplateMakerCSharp [template-folder] [--once] [--delete-generated]";
string? templateFolder = null;
bool once = false;
bool deleteGenerated = false;
foreach (string arg in args)
{
    switch (arg)
    {
        case "--once":
            once = true;
            break;
        case "--delete-generated":
            deleteGenerated = true;
            break;
        case "-h":
        case "--help":
            Console.WriteLine(Usage);
            return 0;
        default:
            if (arg.StartsWith('-'))
            {
                Console.Error.WriteLine($"Unknown option: {arg}");
                Console.Error.WriteLine(Usage);
                return 2;
            }

            if (templateFolder != null)
            {
                Console.Error.WriteLine("Only one template folder can be given.");
                Console.Error.WriteLine(Usage);
                return 2;
            }

            templateFolder = arg;
            break;
    }
}

string folder = Path.GetFullPath(templateFolder ?? ".");
if (!Directory.Exists(folder))
{
    Console.Error.WriteLine($"Template folder not found: {folder}");
    return 2;
}

using ILoggerFactory loggerFactory = LoggerFactory.Create(builder => builder
    .SetMinimumLevel(LogLevel.Information)
    .AddSimpleConsole(options =>
    {
        options.SingleLine = true;
        options.TimestampFormat = "HH:mm:ss ";
    }));
ILogger logger = loggerFactory.CreateLogger("DicomTemplateMaker");

// Not disposed: it lives as long as the process, and the Ctrl+C handler may still run at exit.
var cancellation = new CancellationTokenSource();
Console.CancelKeyPress += (_, e) =>
{
    if (!cancellation.IsCancellationRequested)
    {
        e.Cancel = true;
        Console.Error.WriteLine("Stopping... press Ctrl+C again to end at once.");
        cancellation.Cancel();
    }
};

string templateRs = DicomTemplateRunner.DefaultTemplateRsPath;
var runner = new DicomTemplateRunner(folder, templateRs, logger, TimeProvider.System);
try
{
    if (deleteGenerated)
    {
        DeleteReport deleted = runner.DeleteGenerated(cancellation.Token);
        logger.LogInformation("Deleted {Deleted} generated RT file(s); {Failed} could not be deleted; {Errors} error(s).",
            deleted.Deleted.Count, deleted.Failed.Count, deleted.Errors.Count);
        return deleted.HasFailures ? 1 : 0;
    }

    if (!File.Exists(templateRs))
    {
        logger.LogError("The template RT file {Path} is missing; it must be next to the program.", templateRs);
        return 1;
    }

    if (once)
    {
        RunReport report = runner.RunOnce(cancellation.Token);
        logger.LogInformation("Done: {Summary}.", report.Summary);
        return report.HasErrors ? 1 : 0;
    }

    logger.LogInformation("Watching templates in {Folder}. Press Ctrl+C to stop.", folder);
    await runner.RunAsync(TimeSpan.FromSeconds(3), new CycleSummaryPrinter(logger), cancellation.Token);
    logger.LogInformation("Stopped.");
    return 0;
}
catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
{
    logger.LogWarning("Cancelled before finishing.");
    return 1;
}

/// <summary>
/// Logs each cycle's summary (RTs written, ROI failures, errors, folders waiting). An idle cycle whose summary
/// equals the previous one is not repeated, so a long-running watch does not print a line every 3 s.
/// </summary>
internal sealed class CycleSummaryPrinter : IProgress<RunReport>
{
    private readonly ILogger logger;
    private string? previous;

    public CycleSummaryPrinter(ILogger logger)
    {
        this.logger = logger;
    }

    public void Report(RunReport value)
    {
        string summary = value.Summary;
        bool active = value.WrittenCount > 0 || value.RoiFailureCount > 0 || value.ErrorCount > 0;
        if (active || summary != previous)
        {
            logger.LogInformation("Cycle: {Summary}.", summary);
        }

        previous = summary;
    }
}
