using DicomTemplateMakerGUI.DicomTemplateServices;
using DicomTemplateMakerGUI.Shell;
using Xunit;

namespace DicomTemplateMaker.Presentation.Tests;

public sealed class ShellMessagesTests
{
    [Fact]
    public void Asking_to_use_all_templates_names_the_action_and_the_count()
    {
        string text = ShellMessages.UseAllTemplates("Generate test RTs for", 12, 0);

        Assert.StartsWith("No templates are selected.", text, StringComparison.Ordinal);
        Assert.EndsWith("Generate test RTs for all 12 templates?", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Asking_to_use_all_templates_mentions_selected_ones_hidden_by_the_search()
    {
        Assert.Contains("2 selected templates are hidden by the search", ShellMessages.UseAllTemplates("Export", 5, 2), StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_generated_confirmation_names_templates_folders_and_the_permanent_delete()
    {
        var templates = new[]
        {
            new MonitoredTemplate("Brain", new[] { @"\\server\ct", @"D:\Incoming" }),
            new MonitoredTemplate("Empty", Array.Empty<string>()),
        };

        string text = ShellMessages.ConfirmDeleteGenerated(templates, hiddenSelected: 1, RunnerState.Running);

        Assert.StartsWith("Delete the RTs generated by 1 template?", text, StringComparison.Ordinal);
        Assert.Contains(@"Brain: \\server\ct; D:\Incoming", text, StringComparison.Ordinal);
        Assert.Contains("_UID", text, StringComparison.Ordinal);
        Assert.Contains("permanently", text, StringComparison.Ordinal);
        Assert.Contains("without monitored folders has nothing to delete: Empty.", text, StringComparison.Ordinal);
        Assert.Contains("1 selected template hidden by the current search is left out", text, StringComparison.Ordinal);
        Assert.Contains("The RT generator is stopped before deleting and stays stopped afterwards.", text, StringComparison.Ordinal);
        Assert.Contains("come back", text, StringComparison.Ordinal);
        // The old text promised the resumed generator would not write them again; it wrote them within one scan.
        Assert.DoesNotContain("resumes", text, StringComparison.Ordinal);
        Assert.DoesNotContain("does not write these RTs again", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_generated_confirmation_with_the_generator_stopped_says_starting_it_writes_them_again()
    {
        string text = ShellMessages.ConfirmDeleteGenerated(new[] { new MonitoredTemplate("Brain", new[] { "/ct" }) }, 0, RunnerState.Stopped);

        Assert.DoesNotContain("stopped before deleting", text, StringComparison.Ordinal);
        Assert.Contains("Whenever the RT generator runs, it writes a new RT", text, StringComparison.Ordinal);
        Assert.Contains("remove these folders from the templates' monitored folders", text, StringComparison.Ordinal);
        Assert.DoesNotContain("hidden", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_generated_result_says_the_generator_was_left_stopped()
    {
        var report = new DeleteReport(new[] { "/ct/a.dcm" }, Array.Empty<DeleteFailure>(), Array.Empty<RunError>());

        Assert.Contains("The RT generator is stopped.", ShellMessages.DescribeDeleteGenerated(report, generatorStopped: true), StringComparison.Ordinal);
        Assert.DoesNotContain("generator", ShellMessages.DescribeDeleteGenerated(report), StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_templates_confirmation_names_the_folders_without_a_recycle_bin_as_not_deleted()
    {
        string text = ShellMessages.ConfirmDeleteTemplates(
            new[] { ("Brain", @"C:	\Brain") },
            hiddenSelected: 0,
            new[] { new NotRecyclable("Lung", @"\\server\t\Lung", "it is on a network share") });

        Assert.StartsWith("Move 1 template folder to the Recycle Bin?", text, StringComparison.Ordinal);
        Assert.Contains("This template folder is not deleted", text, StringComparison.Ordinal);
        Assert.Contains(@"Lung  (\\server\t\Lung): it is on a network share", text, StringComparison.Ordinal);
        Assert.Contains("File Explorer", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Changing_the_template_folder_while_the_generator_runs_says_what_each_answer_does()
    {
        string text = ShellMessages.ConfirmChangeRootWhileRunning(@"D:\Drafts");

        Assert.Contains(@"Yes: switch to D:\Drafts and keep the RT generator running there", text, StringComparison.Ordinal);
        Assert.Contains("into the folders they monitor", text, StringComparison.Ordinal);
        Assert.Contains(@"No: switch to D:\Drafts and stop the RT generator", text, StringComparison.Ordinal);
        Assert.Contains("Cancel: keep the current template folder.", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Airtable_write_confirmation_names_the_table_the_templates_and_the_hidden_ones()
    {
        string text = ShellMessages.ConfirmAirtableWrite("UCSD", new[] { ("Prostate", 12), ("Brain", 1) }, hiddenSelected: 1);

        Assert.StartsWith("Update table \"UCSD\" with 2 templates?", text, StringComparison.Ordinal);
        Assert.Contains("Prostate (12 ROIs)", text, StringComparison.Ordinal);
        Assert.Contains("Brain (1 ROI)", text, StringComparison.Ordinal);
        Assert.Contains("change for every site", text, StringComparison.Ordinal);
        Assert.Contains("1 selected template hidden by the current search is left out", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Copy_result_says_the_copies_have_no_monitored_folders_and_lists_failures()
    {
        string text = ShellMessages.DescribeCopies(new[] { ("Brain", "Brain_Copy0") }, new[] { "Lung: disk full" });

        Assert.StartsWith("Copied 1 template:", text, StringComparison.Ordinal);
        Assert.Contains("Brain → Brain_Copy0", text, StringComparison.Ordinal);
        Assert.Contains("no monitored folders, so the RT generator writes no RTs for it", text, StringComparison.Ordinal);
        Assert.Contains("Lung: disk full", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_generated_result_gives_the_count_and_every_failure()
    {
        var report = new DeleteReport(
            new[] { "/ct/a.dcm", "/ct/b.dcm" },
            new[] { new DeleteFailure("/ct/c.dcm", "in use") },
            new[] { new RunError("template 'Brain'", "path missing", "Brain") });

        string text = ShellMessages.DescribeDeleteGenerated(report);

        Assert.StartsWith("Deleted 2 generated RTs.", text, StringComparison.Ordinal);
        Assert.Contains("/ct/c.dcm: in use", text, StringComparison.Ordinal);
        Assert.Contains("template 'Brain': path missing", text, StringComparison.Ordinal);
        Assert.Contains("log", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_templates_confirmation_lists_names_folders_and_hidden_ones()
    {
        string text = ShellMessages.ConfirmDeleteTemplates(new[] { ("Brain", "/t/Brain"), ("Lung", "/t/Lung") }, hiddenSelected: 3);

        Assert.StartsWith("Move 2 template folders to the Recycle Bin?", text, StringComparison.Ordinal);
        Assert.Contains("Brain  (/t/Brain)", text, StringComparison.Ordinal);
        Assert.Contains("Lung  (/t/Lung)", text, StringComparison.Ordinal);
        Assert.Contains("3 selected templates hidden by the current search are left out", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Delete_templates_result_reports_failures_and_unchanged_folders()
    {
        var result = new BulkFolderResult();
        result.Done.Add("/t/Brain");
        result.Failed.Add(new FolderFailure("/t/Lung", "in use"));

        string text = ShellMessages.DescribeDeleteTemplates(result);

        Assert.StartsWith("Moved 1 template folder to the Recycle Bin.", text, StringComparison.Ordinal);
        Assert.Contains("1 template folder was not moved and is unchanged", text, StringComparison.Ordinal);
        Assert.Contains("/t/Lung: in use", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Test_rt_confirmation_states_count_folder_and_that_paths_are_unchanged()
    {
        string text = ShellMessages.ConfirmTestRts(new[] { "Brain", "Lung" }, "/out/Template_Output", 0);

        Assert.StartsWith("Generate test RTs for 2 templates into /out/Template_Output?", text, StringComparison.Ordinal);
        Assert.Contains("monitored folders are not changed", text, StringComparison.Ordinal);
        Assert.Contains("not started", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Test_rt_result_explains_templates_without_an_rt()
    {
        var result = new TestRtResult("/out");
        result.Reports.Add(("Brain", RunnerStatusTests.Report(written: 1)));
        result.Reports.Add(("Lung", new RunReport(DateTimeOffset.UnixEpoch, TimeSpan.Zero, Array.Empty<WrittenRt>(),
            new[] { new SkippedItem("Lung", "/out", "1.2", SkipReason.NoMatch, "no match") }, Array.Empty<RoiFailure>(), Array.Empty<RunError>())));
        result.Reports.Add(("Old", new RunReport(DateTimeOffset.UnixEpoch, TimeSpan.Zero, Array.Empty<WrittenRt>(),
            new[] { new SkippedItem("Old", "/out", "1.2", SkipReason.AlreadyDone, "exists") }, Array.Empty<RoiFailure>(), Array.Empty<RunError>())));

        string text = ShellMessages.DescribeTestRts(result);

        Assert.StartsWith("Wrote 1 test RT into /out.", text, StringComparison.Ordinal);
        Assert.Contains("Lung: the sample CT does not meet the template's DICOM requirements", text, StringComparison.Ordinal);
        Assert.Contains("Old: a test RT for the sample CT is already in the folder.", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Test_rt_result_with_a_copy_error_says_nothing_was_written()
    {
        var result = new TestRtResult("/out");
        result.Errors.Add("disk full");

        Assert.StartsWith("No test RTs were written.", ShellMessages.DescribeTestRts(result), StringComparison.Ordinal);
    }

    [Fact]
    public void Export_overwrite_question_lists_the_existing_files_and_the_choices()
    {
        string text = ShellMessages.ConfirmExportOverwrite("/xml", new[] { "Brain.xml", "Lung.xml" }, 5);

        Assert.Contains("These 2 files already exist in /xml", text, StringComparison.Ordinal);
        Assert.Contains("Brain.xml", text, StringComparison.Ordinal);
        Assert.Contains("Lung.xml", text, StringComparison.Ordinal);
        Assert.Contains("Yes: replace them and write the other 3.", text, StringComparison.Ordinal);
        Assert.Contains("No: keep them and write only the other 3.", text, StringComparison.Ordinal);
        Assert.Contains("Cancel: write nothing.", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Import_replace_question_says_paths_and_requirements_are_kept()
    {
        string text = ShellMessages.ConfirmImportReplace("/t", new[] { "Brain" }, 4);

        Assert.Contains("This template already exists in /t", text, StringComparison.Ordinal);
        Assert.Contains("monitored folders and DICOM requirements are kept", text, StringComparison.Ordinal);
        Assert.Contains("import the other 3", text, StringComparison.Ordinal);
        Assert.Contains("Cancel: import nothing.", text, StringComparison.Ordinal);
    }

    [Fact]
    public void The_problems_line_counts_each_kind()
    {
        var problems = new[]
        {
            new TemplateProblem(TemplateProblemKind.TemplateUnreadable, "A", "x"),
            new TemplateProblem(TemplateProblemKind.TemplateUnreadable, "B", "y"),
            new TemplateProblem(TemplateProblemKind.LegacyFilesKept, "C", "file 1"),
            new TemplateProblem(TemplateProblemKind.LegacyFilesKept, "C", "file 2"),
        };

        Assert.Equal("\u26A0 2 templates cannot be read and are not listed; 1 template has legacy files that were kept.", ShellMessages.ProblemsLine(problems));
        Assert.Equal(string.Empty, ShellMessages.ProblemsLine(Array.Empty<TemplateProblem>()));
    }

    [Fact]
    public void The_problem_details_name_each_problem()
    {
        string text = ShellMessages.NewProblems(new[] { new TemplateProblem(TemplateProblemKind.TemplateUnreadable, "Brain", "Could not read 'x'.") });

        Assert.Contains("Brain: Could not read 'x'.", text, StringComparison.Ordinal);
        Assert.Contains("not shown again", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Unexpected_errors_point_to_the_log()
    {
        string text = ShellMessages.UnexpectedError(new InvalidOperationException("boom"), "/logs");

        Assert.Contains("boom", text, StringComparison.Ordinal);
        Assert.Contains("details are in the log in /logs", text, StringComparison.Ordinal);
    }

    [Fact]
    public void Long_lists_are_cut_with_a_count_of_the_rest()
    {
        string text = ShellMessages.ConfirmTestRts(Enumerable.Range(1, 20).Select(i => "T" + i).ToList(), "/out", 0);

        Assert.Contains("T15", text, StringComparison.Ordinal);
        Assert.DoesNotContain("T16", text, StringComparison.Ordinal);
        Assert.Contains("\u2026 and 5 more.", text, StringComparison.Ordinal);
    }
}
